### ISSUE TITLE
Support for animation XMLs in AAF directory

### ISSUE THREAD

**Issue by RubberDuck01** [Deweh/Native-Animation-Framework#16]
Hi there!

Would it  be possible to code NAF to iterate over Data/AAF directory and search for XMLs there as well as Data/NAF?

Reason being, NAF is currently at the stage of mass adoption - it's the logical next step for animation framework in Fallout 4 modding community, and it should be as compatible with old (AAF) as it can. During the initial set up, one must copy and paste all the animation XMLs from Data/AAF to Data/NAF in order NAF recognizes the animations. While I personally didn't have any issues with it, I bet there are players who did.

This complicates things to even greater extent if you use a lot of animations - I have 520 items in my Data/NAF and it took me a lot of time because I had to overwrite certain animations depending on my load order (patches for animations, tweaks, etc.). 

**Would you consider adding a new function and a simple switch in MCM for NAF to use XMLs from AAF directory?**

It could be complicated, especially when the same animation XML file is found in multiple directories, but it should look at them dynamically by one's plugin order. For example, let's assume I have AnimationMod-1.esp and AnimationMod-2.esp in my plugin order like this:
`AnimationMod-1.esp`
`AnimationMod-2.esp`

This means that _AnimationMod-2.esp_ has **lower priority** (loaded after) _AnimationMod-1.esp_. Because _AnimationMod-2.esp_ is loaded after _AnimationMod-1.esp_, NAF should take the XMLs from AnimationMod-2.

If during the initial check for contents of Data/AAF it finds the same animation XML, it should only take the one whose plugin is loaded last. For example, let's assume '_some_anim_file.xml_' is present in Data/AAF of these mods:
`AnimationMod-1.esp`
`AnimationMod-2.esp`
`AnimationMod-3.esp`

During initial check, it will find _some_anim_file.xml_ 3 times because all the 3 mods contain it. However, because _AnimationMod-3.esp_ is loaded last in plugin order, it should only take that _some_anim_file.xml_ and not take the first two into account.

This is complicated, but I sincerely hope you give it a shot - if you can do this, NAF will get adopted by every single current AAF user immediately! Hopefully you can do something about it, really looking forward to the next NAF update! Keep up the great work!

**Comment by lapolla** [comment]
Such functionality is not needed. Actually that was first suggestion when I met NAF.

Use MO2 "Explore Virtual Folder" feature and duplicate AAF folder to NAF that will appear in Overwrite.

**Comment by RubberDuck01** [comment]
> Such functionality is not needed. Actually that was first suggestion when I met NAF.
> 
> Use MO2 "Explore Virtual Folder" feature and duplicate AAF folder to NAF that will appear in Overwrite.

Thanks! I totally forgot about that feature! I'll close this issue as the requested functionality is unnecessary. Thanks again for replying!

Take care!
